In [ ]:
# Removing NA Values 

In [1]:
import pandas as pd
import numpy as np 

In [2]:
d1 = {'Name' : ['Pankaj' , 'Meghana' , 'David' , 'Lisa'],
     'ID' : [1,2,3,4] , 
     'Salary' : [100 , 200 , np.nan , pd.NaT] ,
     'Role' : ['CEO' , None , np.nan , pd.NaT]}

In [3]:
df = pd.DataFrame(d1)
print('Actual Dataframe :\n', df)

Actual Dataframe :
       Name  ID Salary  Role
0   Pankaj   1    100   CEO
1  Meghana   2    200  None
2    David   3    NaN   NaN
3     Lisa   4    NaT   NaT


In [4]:
# Drop all rows with any null values :


df1 = df.dropna(how = 'any')

print('Processed data frame:\n',df1)

Processed data frame:
      Name  ID Salary Role
0  Pankaj   1    100  CEO


In [5]:
df.dropna(how = 'any' , inplace = True)
print(df)


     Name  ID Salary Role
0  Pankaj   1    100  CEO


In [6]:
d1 = {'Name' : ['Pankaj' , 'Meghana' , 'David' , pd.NaT],
     'ID' : [1,2,3,np.nan] , 
     'Salary' : [100 , 200 , np.nan , pd.NaT] ,
     'Role' : [None , None , np.nan , pd.NaT]}

df = pd.DataFrame(d1)
print('Actual Dataframe :\n', df)

# drop rows

df1 = df.dropna(how = 'all' )
print('Processed data frame 1:\n',df1)

df1 = df.dropna(how = 'all' , axis = 1)
print('Processed data frame 2:\n',df1)

Actual Dataframe :
       Name   ID Salary Role
0   Pankaj  1.0    100  NaT
1  Meghana  2.0    200  NaT
2    David  3.0    NaN  NaT
3      NaT  NaN    NaT  NaT
Processed data frame 1:
       Name   ID Salary Role
0   Pankaj  1.0    100  NaT
1  Meghana  2.0    200  NaT
2    David  3.0    NaN  NaT
Processed data frame 2:
       Name   ID Salary
0   Pankaj  1.0    100
1  Meghana  2.0    200
2    David  3.0    NaN
3      NaT  NaN    NaT


In [7]:
# Imputing null NA values

d1 = {'Name' : ['Pankaj' , 'Meghana' , 'David' , 'Lisa'],
     'ID' : [1,2,3,4] , 
     'Salary' : [100 , 200 , np.nan , pd.NaT] ,
     'Role' : ['CEO' , 'CTO' , 'CPO' , 'CIO']}

df = pd.DataFrame(d1)
print('Actual Dataframe :\n', df)

Actual Dataframe :
       Name  ID Salary Role
0   Pankaj   1    100  CEO
1  Meghana   2    200  CTO
2    David   3    NaN  CPO
3     Lisa   4    NaT  CIO


In [8]:
# Getting count of Null Vlaue across all columns 

df.isnull().sum()


Name      0
ID        0
Salary    2
Role      0
dtype: int64

IMPUTING EXAMPLE :

In [9]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df.head()

Name  ID  Salary Role
0   Pankaj   1   100.0  CEO
1  Meghana   2   200.0  CTO
2    David   3   150.0  CPO
3     Lisa   4   150.0  CIO

In [10]:
df.isnull().sum()

Name      0
ID        0
Salary    0
Role      0
dtype: int64

In [11]:
# Min max Scaler

from numpy import asarray
from sklearn.preprocessing import MinMaxScaler

In [12]:
# Define the Data

data = asarray([[100, 0.001],
               [8, 0.05],
               [50, 0.005],
               [88, 0.07],
               [4, 0.1]])

print('Actual Data :\n ', data)

Actual Data :
  [[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]


In [13]:
# Define Min Max Scaler:

scaler = MinMaxScaler()

# Transform the data

scaled = scaler.fit_transform(data)

print('Scaled output :\n ', scaled)

Scaled output :
  [[1.         0.        ]
 [0.04166667 0.49494949]
 [0.47916667 0.04040404]
 [0.875      0.6969697 ]
 [0.         1.        ]]


In [1]:
# Standard Scaler

from numpy import asarray
from sklearn.preprocessing import StandardScaler

#define the data

data = asarray([[100,0.001],
               [8,0.05],
               [50,0.005],
               [88,0.07],
               [4,0.1]])

print('Actual Data :\n ', data)

# Define Standard Scaler :

scaler = StandardScaler()

# Transform the data :

scaled = scaler.fit_transform(data)

print('Scaled output :\n ', scaled)

Actual Data :
  [[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]
Scaled output :
  [[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]
